// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYqzqhyeE-6_ZTUDWLiupoROtXOd4fMGQ',
    appId: '1:879713109318:web:ba6d73b15685cba5a4d147',
    messagingSenderId: '879713109318',
    projectId: 'mobile-app-9f7a6',
    authDomain: 'mobile-app-9f7a6.firebaseapp.com',
    storageBucket: 'mobile-app-9f7a6.firebasestorage.app',
    measurementId: 'G-DPEKQEYJ83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV2J7NOPnTG_bt0wfglWNRVT1VFXRkWtM',
    appId: '1:879713109318:android:061c65c0ca1e1bfea4d147',
    messagingSenderId: '879713109318',
    projectId: 'mobile-app-9f7a6',
    storageBucket: 'mobile-app-9f7a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5CKUdJnfVoBDsu2L9BPMzsR6GlOWzVUs',
    appId: '1:879713109318:ios:bd872a4714867120a4d147',
    messagingSenderId: '879713109318',
    projectId: 'mobile-app-9f7a6',
    storageBucket: 'mobile-app-9f7a6.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5CKUdJnfVoBDsu2L9BPMzsR6GlOWzVUs',
    appId: '1:879713109318:ios:bd872a4714867120a4d147',
    messagingSenderId: '879713109318',
    projectId: 'mobile-app-9f7a6',
    storageBucket: 'mobile-app-9f7a6.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYqzqhyeE-6_ZTUDWLiupoROtXOd4fMGQ',
    appId: '1:879713109318:web:9a4a784cd61b6e8ca4d147',
    messagingSenderId: '879713109318',
    projectId: 'mobile-app-9f7a6',
    authDomain: 'mobile-app-9f7a6.firebaseapp.com',
    storageBucket: 'mobile-app-9f7a6.firebasestorage.app',
    measurementId: 'G-8NWNQ20EP2',
  );
}
